### ISSUE TITLE
Create DataStructure.py for each major data structure

### ISSUE THREAD

**Issue by raivatshah** [sushinoya/fundamentals#2]
Eg a stack.py with the stack class and its implementation using either linked-list or array.

**Comment by sushinoya** [comment]
The stack in the doc does use an array (i.e a python list). It is not encapsulated within a class because the point is to be simple. Unless you have specific use cases of a Stack class for basic algorithms that an array can't cover, I don't think we need a Stack class.

**Comment by sushinoya** [comment]
Oh I read that incorrectly because I read the description inste that you take in class. ad of the title. But still I feel like `wontfix` holds because my aim is to not create a library of useful data structures. It is more like notes that you take in a class.
